on: push
name: 🚀 Deploy website on push
jobs:
  web-deploy:
    name: 🎉 Deploy
    runs-on: ubuntu-latest
    steps:
    - name: 🚚 Get latest code
      uses: actions/checkout@v2.3.2
    
    - name: 📂 Sync files
      uses: SamKirkland/FTP-Deploy-Action@4.0.0
      with:
        server: http://access811905793.webspace-data.io/
        username: u99623908
        password: ${{ .4%w5?r7nBnY75M+[PFm }}
        protocol: ftps
        port: 22
        server-dir:	/clickandbuilds/Studiokrack/wp-content/plugins/email-signature-generator
