# This is a basic workflow to help you get started with Actions

on: push
name: 🚀 Deploy website on push
jobs:
  web-deploy:
    name: 🎉 Deploy
    runs-on: ubuntu-latest
    steps:
    - name: 🚚 Get latest code
      uses: actions/checkout@v2.3.2

    - name: 📂 Sync files
      uses: SamKirkland/FTP-Deploy-Action@4.0.0
      with:
        server: ftp.access811905793.webspace-data.io/
        username: u99623908
        password: ${{ secrets.KRACK_FTP_KEY }}
        protocol: ftps
        port: 22
        server-dir:	/clickandbuilds/Studiokrack/wp-content/plugins/email-signature-generator/
